name: Create PR for New Branch

on:
  create:
    # This event will be triggered when a new branch is created
    branches:
      - 'test15'

jobs:
  create-pr:
    if: contains(github.ref_name, '**test**')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code into subdirectory
        uses: actions/checkout@v4
        with:
          repository: huiwangredhat/trestle-repo
          ref: test15
          path: trestle-repo
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "test15"  # Source branch (in the subdirectory)
          base: "main"               # Target branch (main)
          title: "Sync Cac Automatic updates from trestle-bot"   # Customize PR title
          body: "Description of changes in the specified subdirectory"  # PR description in the subdirectory
          draft: false 