name: Create Pull Request
on:
  create:
    ref_type: branch

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}  # Use the newly created branch name
          base: main  # The base branch you want to merge into
          title: "Auto PR for ${{ github.ref_name }}"
          body: "This PR is automatically created for the new branch ${{ github.ref_name }}."
          draft: false
