name: Create PR for New Branch

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  create-pr:
    if: github.event.created
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code into subdirectory
        uses: actions/checkout@v4
        with:
          ref: test17
          path: trestle-repo
      - name: Create Pull Request
        id: crp
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: test17
          base: "main"               # Target branch (main)
          title: "Sync Cac Automatic updates from trestle-bot"   # Customize PR title
          body: "Description of changes in the specified subdirectory"  # PR description in the subdirectory
          draft: false 
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"