name: Check for New 'sync_cac/' Branches and Create PR

on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 PM (adjust as necessary)
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  create-pr-for-new-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout the repository code
        uses: actions/checkout@v4

      - name: Fetch all remote branches
        run: |
          git fetch --all
          echo "Fetching all branches from the remote repository."

      - name: Get list of sync_cac/ branches
        id: get-sync-cac-branches
        run: |
          # List all remote branches starting with 'sync_cac/'
          sync_cac_branches=$(git branch -r | grep 'origin/sync_cac/' | sed 's/origin\///')
          echo "sync_cac/ branches found: $sync_cac_branches"
          # Create a PR for each new sync_cac/ branch
          for branch in $sync_cac_branches; do
            echo "Creating PR for new branch: $branch"
            curl -X POST https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{
              "title": "Auto PR for '\"$branch\"'",
              "head": "'\"$branch\"'",
              "base": "main",
              "body": "This is an auto-created PR for the new branch '$branch'",
              "draft": true
              }'
          done
      
      - name: Create Pull Request
        id: crp
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync_cac/test  # Source branch (in the subdirectory)
          base: "main"               # Target branch (main)
          title: "Sync Cac Automatic updates from trestle-bot"   # Customize PR title
          body: "Description of changes in the specified subdirectory"  # PR description in the subdirectory
          draft: false 