name: Create PR for New Branch

on:
  push:
    # This event will be triggered when a new branch is created
    branches-ignore: ["main"]
    branches:
      - '**test**'

jobs:
  create-pr:
    if: contains(github.ref_name, '**test**')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: action/checkout@v4
      - name: Create Pull Request action
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Use your GITHUB_TOKEN to authenticate
          title: "[Auto PR] $BRANCH_NAME"  # Specify a title for your pull request
          body: "This pull request was automatically created for the new branch $BRANCH_NAME."  # Add any additional information you want in the PR body
          branch: ${{github.ref_name}}
          base: "main"
          draft: false  # Whether the PR should be created as a draft (false means it will be submitted as a regular PR)