name: Create Pull Request for sync CAC content
on:
  schedule:
    - cron: '0 12 * * *'  # Run daily at 12:00 PM (adjust as necessary)
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4 #v4
        with:
          name: cac_output
      - name: check details
        run: ls
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "output.json"